import nlp from 'compromise'

const IRREGULAR_MAP: Record<string, string> = {
  ran: 'run',
  running: 'run',
  runs: 'run',
  went: 'go',
  going: 'go',
  goes: 'go',
  gone: 'go',
  was: 'be',
  were: 'be',
  been: 'be',
  being: 'be',
  am: 'be',
  is: 'be',
  are: 'be',
  had: 'have',
  has: 'have',
  having: 'have',
  did: 'do',
  does: 'do',
  doing: 'do',
  done: 'do',
  said: 'say',
  saying: 'say',
  says: 'say',
  made: 'make',
  making: 'make',
  makes: 'make',
  took: 'take',
  taking: 'take',
  takes: 'take',
  taken: 'take',
  came: 'come',
  coming: 'come',
  comes: 'come',
  saw: 'see',
  seeing: 'see',
  sees: 'see',
  seen: 'see',
  knew: 'know',
  knowing: 'know',
  knows: 'know',
  known: 'know',
  got: 'get',
  getting: 'get',
  gets: 'get',
  gotten: 'get',
  gave: 'give',
  giving: 'give',
  gives: 'give',
  given: 'give',
  found: 'find',
  finding: 'find',
  finds: 'find',
  thought: 'think',
  thinking: 'think',
  thinks: 'think',
  told: 'tell',
  telling: 'tell',
  tells: 'tell',
  became: 'become',
  becoming: 'become',
  becomes: 'become',
  left: 'leave',
  leaving: 'leave',
  leaves: 'leave',
  felt: 'feel',
  feeling: 'feel',
  feels: 'feel',
  put: 'put',
  putting: 'put',
  puts: 'put',
  brought: 'bring',
  bringing: 'bring',
  brings: 'bring',
  began: 'begin',
  beginning: 'begin',
  begins: 'begin',
  begun: 'begin',
  kept: 'keep',
  keeping: 'keep',
  keeps: 'keep',
  held: 'hold',
  holding: 'hold',
  holds: 'hold',
  wrote: 'write',
  writing: 'write',
  writes: 'write',
  written: 'write',
  stood: 'stand',
  standing: 'stand',
  stands: 'stand',
  heard: 'hear',
  hearing: 'hear',
  hears: 'hear',
  let: 'let',
  letting: 'let',
  lets: 'let',
  meant: 'mean',
  meaning: 'mean',
  means: 'mean',
  set: 'set',
  setting: 'set',
  sets: 'set',
  met: 'meet',
  meeting: 'meet',
  meets: 'meet',
  paid: 'pay',
  paying: 'pay',
  pays: 'pay',
  sat: 'sit',
  sitting: 'sit',
  sits: 'sit',
  spoke: 'speak',
  speaking: 'speak',
  speaks: 'speak',
  spoken: 'speak',
  lay: 'lie',
  lying: 'lie',
  lies: 'lie',
  lain: 'lie',
  led: 'lead',
  leading: 'lead',
  leads: 'lead',
  read: 'read',
  reading: 'read',
  reads: 'read',
  grew: 'grow',
  growing: 'grow',
  grows: 'grow',
  grown: 'grow',
  lost: 'lose',
  losing: 'lose',
  loses: 'lose',
  fell: 'fall',
  falling: 'fall',
  falls: 'fall',
  fallen: 'fall',
  sent: 'send',
  sending: 'send',
  sends: 'send',
  built: 'build',
  building: 'build',
  builds: 'build',
  understood: 'understand',
  understanding: 'understand',
  understands: 'understand',
  drew: 'draw',
  drawing: 'draw',
  draws: 'draw',
  drawn: 'draw',
  broke: 'break',
  breaking: 'break',
  breaks: 'break',
  broken: 'break',
  spent: 'spend',
  spending: 'spend',
  spends: 'spend',
  cut: 'cut',
  cutting: 'cut',
  cuts: 'cut',
  rose: 'rise',
  rising: 'rise',
  rises: 'rise',
  risen: 'rise',
  drove: 'drive',
  driving: 'drive',
  drives: 'drive',
  driven: 'drive',
  bought: 'buy',
  buying: 'buy',
  buys: 'buy',
  wore: 'wear',
  wearing: 'wear',
  wears: 'wear',
  worn: 'wear',
  chose: 'choose',
  choosing: 'choose',
  chooses: 'choose',
  chosen: 'choose',
  sought: 'seek',
  seeking: 'seek',
  seeks: 'seek',
  threw: 'throw',
  throwing: 'throw',
  throws: 'throw',
  thrown: 'throw',
  caught: 'catch',
  catching: 'catch',
  catches: 'catch',
  dealt: 'deal',
  dealing: 'deal',
  deals: 'deal',
  won: 'win',
  winning: 'win',
  wins: 'win',
  taught: 'teach',
  teaching: 'teach',
  teaches: 'teach',
  bit: 'bite',
  biting: 'bite',
  bites: 'bite',
  bitten: 'bite',
  blew: 'blow',
  blowing: 'blow',
  blows: 'blow',
  blown: 'blow',
  drank: 'drink',
  drinking: 'drink',
  drinks: 'drink',
  drunk: 'drink',
  ate: 'eat',
  eating: 'eat',
  eats: 'eat',
  eaten: 'eat',
  flew: 'fly',
  flying: 'fly',
  flies: 'fly',
  flown: 'fly',
  forgot: 'forget',
  forgetting: 'forget',
  forgets: 'forget',
  forgotten: 'forget',
  froze: 'freeze',
  freezing: 'freeze',
  freezes: 'freeze',
  frozen: 'freeze',
  hid: 'hide',
  hiding: 'hide',
  hides: 'hide',
  hidden: 'hide',
  hit: 'hit',
  hitting: 'hit',
  hits: 'hit',
  hung: 'hang',
  hanging: 'hang',
  hangs: 'hang',
  hurt: 'hurt',
  hurting: 'hurt',
  hurts: 'hurt',
  laid: 'lay',
  laying: 'lay',
  lays: 'lay',
  lent: 'lend',
  lending: 'lend',
  lends: 'lend',
  lit: 'light',
  lighting: 'light',
  lights: 'light',
  rode: 'ride',
  riding: 'ride',
  rides: 'ride',
  ridden: 'ride',
  rang: 'ring',
  ringing: 'ring',
  rings: 'ring',
  rung: 'ring',
  sang: 'sing',
  singing: 'sing',
  sings: 'sing',
  sung: 'sing',
  sank: 'sink',
  sinking: 'sink',
  sinks: 'sink',
  sunk: 'sink',
  slept: 'sleep',
  sleeping: 'sleep',
  sleeps: 'sleep',
  slid: 'slide',
  sliding: 'slide',
  slides: 'slide',
  sold: 'sell',
  selling: 'sell',
  sells: 'sell',
  shook: 'shake',
  shaking: 'shake',
  shakes: 'shake',
  shaken: 'shake',
  shone: 'shine',
  shining: 'shine',
  shines: 'shine',
  shot: 'shoot',
  shooting: 'shoot',
  shoots: 'shoot',
  shut: 'shut',
  shutting: 'shut',
  shuts: 'shut',
  stole: 'steal',
  stealing: 'steal',
  steals: 'steal',
  stolen: 'steal',
  stuck: 'stick',
  sticking: 'stick',
  sticks: 'stick',
  struck: 'strike',
  striking: 'strike',
  strikes: 'strike',
  stricken: 'strike',
  swam: 'swim',
  swimming: 'swim',
  swims: 'swim',
  swum: 'swim',
  swung: 'swing',
  swinging: 'swing',
  swings: 'swing',
  tore: 'tear',
  tearing: 'tear',
  tears: 'tear',
  torn: 'tear',
  woke: 'wake',
  waking: 'wake',
  wakes: 'wake',
  woken: 'wake',
  withdrew: 'withdraw',
  withdrawing: 'withdraw',
  withdraws: 'withdraw',
  withdrawn: 'withdraw',
  // Common plural nouns
  children: 'child',
  men: 'man',
  women: 'woman',
  people: 'person',
  teeth: 'tooth',
  feet: 'foot',
  mice: 'mouse',
  geese: 'goose',
  oxen: 'ox',
  crises: 'crisis',
  phenomena: 'phenomenon',
  analyses: 'analysis',
  theses: 'thesis',
  hypotheses: 'hypothesis',
  criteria: 'criterion',
  data: 'datum',
  media: 'medium',
  bacteria: 'bacterium',
  curricula: 'curriculum',
  indices: 'index',
  appendices: 'appendix',
  matrices: 'matrix',
  vertices: 'vertex',
  diagnoses: 'diagnosis',
  prognoses: 'prognosis',
  bases: 'basis',
  axes: 'axis',
  oases: 'oasis',
  parentheses: 'parenthesis',
  synopses: 'synopsis',
  emphases: 'emphasis',
  stimuli: 'stimulus',
  alumni: 'alumnus',
  foci: 'focus',
  radii: 'radius',
  nuclei: 'nucleus',
  syllabi: 'syllabus',
  cacti: 'cactus',
  fungi: 'fungus',
}

export function lemmatize(word: string): string {
  const lower = word.toLowerCase().trim()
  if (lower.length <= 2) return lower

  // Check irregular map first
  if (IRREGULAR_MAP[lower]) return IRREGULAR_MAP[lower]

  // Use compromise
  try {
    const doc = nlp(lower)
    const json = doc.json({ normal: true })
    const terms = (json as Array<{ terms: Array<{ normal: string }> }>)?.[0]?.terms
    if (terms && terms.length > 0) {
      const normal = terms[0].normal
      if (normal && normal !== lower && normal.length > 1) {
        return normal
      }
    }
  } catch {
    // compromise failed, fall through
  }

  // Simple suffix stripping as fallback
  if (lower.endsWith('ing') && lower.length > 5) {
    const base = lower.slice(0, -3)
    if (lower[lower.length - 4] === lower[lower.length - 5]) {
      return base.slice(0, -1)
    }
    return base
  }
  if (lower.endsWith('ed') && lower.length > 5) {
    const base = lower.slice(0, -2)
    if (lower[lower.length - 3] === lower[lower.length - 4]) {
      return base.slice(0, -1)
    }
    return base
  }
  if (lower.endsWith('es') && lower.length > 4) {
    return lower.slice(0, -2)
  }
  if (lower.endsWith('s') && !lower.endsWith('ss') && lower.length > 3) {
    return lower.slice(0, -1)
  }
  if (lower.endsWith('ly') && lower.length > 4) {
    return lower.slice(0, -2)
  }

  return lower
}

export const lemmatizer = { lemmatize }